version: "3"
services:
  # the main image, this is the application
  web: &elixir
    image: nfl-rushing:dev
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.dev
    command: sh -c "mix deps.get && mix phx.server"
    working_dir: "/nfl-rushing"
    ports:
      - "4000:4000"
    volumes:
      - ./:/nfl-rushing
    links:
      - postgres

  postgres: &postgres
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: "rushing_dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  test:
    <<: *elixir
    command: mix test
    links:
      - postgres-test

  # Not running credo as part of test for now
  credo:
    <<: *elixir
    command: mix credo

  postgres-test:
    <<: *postgres
    environment:
      POSTGRES_DB: "rushing_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  npm-install:
    <<: *elixir
    working_dir: "/nfl-rushing/assets"
    command: "npm install"