FROM elixir:1.10-alpine

ENV MIX_HOME=/opt/mix

RUN apk --update add bash openssl nodejs npm inotify-tools \
  && rm -rf /var/cache/apk/*

WORKDIR /nfl-rushing
COPY ./ /nfl-rushing

RUN mix local.hex --force \
  && mix local.rebar --force \
  && mix deps.get